apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbox.fullname" . }}-env
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    helm.sh/chart: {{ include "netbox.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if .Values.postgresql.host }}
  DB_HOST: '{{ .Values.postgresql.host }}'
{{- else }}
  DB_HOST: '{{ .Release.Name }}-postgresql'
{{- end }}
{{- if .Values.redis.host }}
  REDIS_HOST: '{{ .Values.redis.host }}'
{{- else }}
  REDIS_HOST: '{{ include "redis.child.fullname" . | trim }}-master'
{{- end }}
  DB_NAME: '{{ .Values.postgresql.postgresqlDatabase }}'
  ALLOWED_HOSTS: '{{ .Values.allowedHosts }}'
  EMAIL_FROM: '{{ .Values.emailFrom }}'
  EMAIL_PORT: '{{ .Values.emailPort }}'
  EMAIL_SERVER: '{{ .Values.emailServer }}'
  EMAIL_TIMEOUT: '{{ .Values.emailTimeout }}'
  SUPERUSER_NAME: '{{ .Values.superuser.name }}'
  SUPERUSER_EMAIL: '{{ .Values.superuser.email }}'
{{- range $key, $value := .Values.extraEnvs }}
  {{ $key }}: '{{ $value }}'
{{- end }}
